### ISSUE TITLE
v0.1.5 release request

### ISSUE THREAD

**Issue by asw-dev** [wdv4758h/cargo-arch#18]
I struggled for a bit trying to track down why "usr/.crates2.json" was present in the created package, only to discover it has had a fix for over a year (#13).

I was able to get it working by installing cargo-arch via git as per the README, but it would be nice to get an updated release.

-Thank you

**Comment by wdv4758h** [comment]
The version 0.1.5 is pulibshed to crates.io.

The old TravisCI setup is broken (as they drop `travis-ci.org` and move to `travis-ci.com` with different policy), so no prebuilt on GitHub release for now. Probably should move the CI to GitHub Actions :P
