### ISSUE TITLE
fails to build out of the box

### ISSUE THREAD

**Issue by cardoe** [wdv4758h/cargo-arch#6]
I tried to use this in the source of one of my binary crates and it failed out of the box.
```
[build@c843c0d03f3a source]$ cargo arch
==> ERROR: mycrate is not available for the 'x86_64' architecture.
```
In the `PKGBUILD` file the following definition is there: `arch=()` which makes sense why this fails.

**Comment by wdv4758h** [comment]
acutally, you can assign the arch you want (also other fields in PKGBUILD)

put this in `Cargo.toml` :
```
[package.metadata.arch]
arch = ["x86_64"]
```

see also: https://github.com/wdv4758h/cargo-arch/blob/f225a8bc30740d79c15bb642f9e1ec5d714c58af/Cargo.toml#L18-L19

**Comment by cardoe** [comment]
It was just a bit unexpected that the default arch that Arch Linux supports doesn't work out of the box and that there's no real information about needing that key in the README. And that the code marks this field as `Option` when it clearly is not.

**Comment by wdv4758h** [comment]
good point
we should have a default value for this field, and let people customize it when needed (e.g. building for Arch Linux ARM).

**Comment by cardoe** [comment]
PR incoming.
