### ISSUE TITLE
make depends is not set

### ISSUE THREAD

**Issue by cardoe** [wdv4758h/cargo-arch#7]
To build a Rust package you need: `makedepends=('rust' 'cargo')` but this crate sets it to an empty set.

**Comment by wdv4758h** [comment]
This should be able to set via `Cargo.toml` too. However, `PKGBUILD` accept the names without `,`, but the current implementation will have `,` between them. Patches are welcome.

The `makedepends` can be assigned from `Cargo.toml` like this:

```
[package.metadata.arch]
makedepends = ["rust", "cargo"]
```
